
version: '3'
services:
  bridge:
    build:
      context: .
    container_name: bridge
    environment:
      - KEYSTORE_PASSWORD=password
    command: --config /config/config.json
    volumes:
      - ./config:/config
      - ./keys:/keys/
    network_mode: host